### ISSUE TITLE
Chocolatey 2.0 creates shims for virtual/meta-pacakge

### ISSUE THREAD

**Issue by davidkna** [chocolatey/choco#3204]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.

### What You Are Seeing?

Chocolatey creates for a meta-package that does not contain any executables.

### What is Expected?

No shim is created.

### How Did You Get This To Happen?

1. Run: `choco install starship`
2. Observe that chocolatey creates a shim `C:\ProgramData\chocolatey\lib\starship\lib\starship\tools\starship.exe`, despite the package being empty.
3. `Invoke-Expression (&starship init powershell)` no longer works properly: ```
C:\ProgramData\chocolatey\lib\starship\tools\starship.exe: The term 'C:\ProgramData\chocolatey\lib\starship\tools\starship.exe' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.```

### System Details

* Operating System:
* Windows PowerShell version:
* Chocolatey CLI Version:
* Chocolatey Licensed Extension version:
* Chocolatey License type:
* Terminal/Emulator:

### Installed Packages

```bash
N/A
```

### Output Log

```bash
I'm not on a Windows machine right now, I can add this if necessary.
```

### Additional Context

starship/starship#5227

**Comment by pauby** [comment]
Before we can look at this please go back to the issue section above and complete all of the sections. Please don't miss any.

Please add the details above and not in a new comment.

Thanks

**Comment by davidkna** [comment]
Updated, but I'm not posting the log because this time it didn't create the shim this time. The last time I tried it, like in the other issue, I got a message that a shim was created.

**Comment by pauby** [comment]
I can't reproduce this issue.

Note that the `starship` package installs `starship.install`. The shim for that is created correctly. There is no shim created for the `starship` package (as there is no EXE to create it from).

![image](https://github.com/chocolatey/choco/assets/12760779/46cca680-49c2-4925-be92-35ec4d077869)

![image](https://github.com/chocolatey/choco/assets/12760779/e473b1ff-720c-4cdc-a5c9-f14ebbc79d97)

There is no `$env:chocolateyInstall\lib\starship\lib` folder created.

![image](https://github.com/chocolatey/choco/assets/12760779/cc5ba552-b2eb-48cc-9d42-ccb9f34d592c)

`Invoke-Expression (&starship init powershell)` works correctly.

![image](https://github.com/chocolatey/choco/assets/12760779/4249c615-e3d8-425d-9ed4-70233cfddc66)

**Comment by pakoito** [comment]
Logs for 1.4: https://github.com/starship/starship/issues/5227#issuecomment-1585226984

Logs for 2.0:  https://github.com/starship/starship/issues/5227#issuecomment-1585229000

**Comment by cobrabr** [comment]
Uninstalling both `starship` and `starship.install` then reinstalling `starship` worked for me. If it makes any difference, I'm using Chocolatey 2.1.0-alpha-20230608.

**Comment by pauby** [comment]
@cobrabr just to be clear, you got this issue when upgrading from a previous version?

Uninstalling and reinstalling resolved the issue?

And you were using the same version of Chocolatey CLI during the upgrade, uninstall and install again?

**Comment by cobrabr** [comment]
@pauby Yes to all 3 questions. :)

**Comment by pauby** [comment]
@cobrabr Thank you for that!

It looks like it may be [this issue](https://github.com/chocolatey/choco/issues/3206) that is causing the problem.

**Comment by gep13** [comment]
To further follow up with this one, I went looking for existing issues regarding the creation of a new Chocolatey CLI command for verifying the current state of a system, and I found this issue:

https://github.com/chocolatey/choco/issues/1757

I believe that this one would be extended to include the verification (check) of existing shims, to ensure that the target of the shim is still in place.

**Comment by pakoito** [comment]
Thank you for the in-depth explanation @gep13! Is there any way to manually remove the shim while `choco verify` is in development?

**Comment by TheCakeIsNaOH** [comment]
> Is there any way to manually remove the shim while choco verify is in development?

Delete the shim `.exe` from `$env:ChocolateyInstall\bin`. So if Chocolatey CLI is installed to the default location that would be `C:\programdata\chocolatey\bin\starship.exe`

**Comment by TheCakeIsNaOH** [comment]
I think there are a number of things that could be improved with regard to shim management, here are a couple of issues that are all partially interrelated:
https://github.com/chocolatey/choco/issues/1670
https://github.com/chocolatey/choco/issues/3
https://github.com/chocolatey/choco/issues/1108
https://github.com/chocolatey/choco/issues/1515

I have some notes somewhere on my thoughts for this, but I was waiting on https://github.com/chocolatey/choco/pull/2003 to be merged first before looking into it again.

**Comment by gep13** [comment]
> @pakoito said...
Thank you for the in-depth explanation @gep13! Is there any way to manually remove the shim while choco verify is in development?

You are very welcome! As @TheCakeIsNaOH mentioned, in the absence of the `choco verify` command, if you find a shim that has been orphaned (you can see where a shim is pointed at by using `<shim-name>.exe --shimgen-help`) you can simply delete that shim from within the bin folder.

**Comment by cobrabr** [comment]
Thanks all for the extra info, it's much appreciated! Looking forward to having `choco verify` available to clean up my local Chocolatey environment. 

@pakoito, I'm pretty sure [bcurran3's choco-cleaner](https://github.com/bcurran3/ChocolateyPackages/tree/master/choco-cleaner) cleans up orphaned shims (along with various other Chocolatey residuals), if you're looking for an automated solution for now.

**Comment by pauby** [comment]
@pakoito @cobrabr 

> I'm pretty sure [bcurran3's choco-cleaner](https://github.com/bcurran3/ChocolateyPackages/tree/master/choco-cleaner) cleans up orphaned shims (along with various other Chocolatey residuals), if you're looking for an automated solution for now.

We do not support or recommend that you use that package, as it removes or modifies things that should not be changed. As a result, you may end up in a situation with a broken Chocolatey CLI installation.

**Comment by cobrabr** [comment]
@pauby Interesting, good to know. I've been using it forever, never had any issues with it, but will keep that in mind. Thanks for the heads-up!
