### ISSUE TITLE
Ensure required documentation is complete for next release

### ISSUE THREAD

**Issue by gep13** [chocolatey/choco#3257]
For the upcoming release of Chocolatey CLI, a number of documentation changes need to be made.

This is a tracking issue, to ensure that these get completed.

The issues in question are:

```[tasklist]
### Tasks
- [ ] https://github.com/chocolatey/docs/issues/773
- [ ] https://github.com/chocolatey/docs/issues/772
- [ ] https://github.com/chocolatey/docs/issues/771
- [ ] https://github.com/chocolatey/docs/issues/770
```
